package hackrf;

import com.sun.jna.Callback;
import com.sun.jna.Library;
import com.sun.jna.ptr.DoubleByReference;

/**
 * JNA Wrapper for library <b>hackrf-sweep</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class HackrfSweepLibrary implements Library {
    public interface hackrf_sweep_lib_start__fft_power_callback_callback extends Callback {
        void apply(double fft_bin_width_callback, DoubleByReference freqStart, DoubleByReference powerdBm);
    }

    public static native int hackrf_lib_start(hackrf_sweep_lib_start__fft_power_callback_callback _fft_power_callback,
                                              int freq_hz, int sample_rate_hz, int fft_size, int lna_gain, int vga_gain, int bw);

    /**
     * Original signature : <code>void hackrf_lib_stop()</code>
     */
    public static native void hackrf_lib_stop();
}
